import { Group, Item } from "./types";

export const defaultGroups: Group[] = [
  { id: "g1", name: "Group 1", teams: [] },
  { id: "g2", name: "Group 2", teams: [] },
];

export const cards: Item[] = [
  { id: "1", name: "Ace of Spades" },
  { id: "2", name: "2 of Spades" },
  { id: "3", name: "3 of Spades" },
  { id: "4", name: "4 of Spades" },
  { id: "5", name: "5 of Spades" },
  { id: "6", name: "6 of Spades" },
  { id: "7", name: "7 of Spades" },
  { id: "8", name: "8 of Spades" },
  { id: "9", name: "9 of Spades" },
  { id: "10", name: "10 of Spades" },
  { id: "11", name: "Jack of Spades" },
  { id: "12", name: "Queen of Spades" },
  { id: "13", name: "King of Spades" },
  { id: "14", name: "Ace of Hearts" },
  { id: "15", name: "2 of Hearts" },
  { id: "16", name: "3 of Hearts" },
  { id: "17", name: "4 of Hearts" },
  { id: "18", name: "5 of Hearts" },
  { id: "19", name: "6 of Hearts" },
  { id: "20", name: "7 of Hearts" },
  { id: "21", name: "8 of Hearts" },
  { id: "22", name: "9 of Hearts" },
  { id: "23", name: "10 of Hearts" },
  { id: "24", name: "Jack of Hearts" },
  { id: "25", name: "Queen of Hearts" },
  { id: "26", name: "King of Hearts" },
  { id: "27", name: "Ace of Diamonds" },
  { id: "28", name: "2 of Diamonds" },
  { id: "29", name: "3 of Diamonds" },
  { id: "30", name: "4 of Diamonds" },
  { id: "31", name: "5 of Diamonds" },
  { id: "32", name: "6 of Diamonds" },
  { id: "33", name: "7 of Diamonds" },
  { id: "34", name: "8 of Diamonds" },
  { id: "35", name: "9 of Diamonds" },
  { id: "36", name: "10 of Diamonds" },
  { id: "37", name: "Jack of Diamonds" },
  { id: "38", name: "Queen of Diamonds" },
  { id: "39", name: "King of Diamonds" },
  { id: "40", name: "Ace of Clubs" },
  { id: "41", name: "2 of Clubs" },
  { id: "42", name: "3 of Clubs" },
  { id: "43", name: "4 of Clubs" },
  { id: "44", name: "5 of Clubs" },
  { id: "45", name: "6 of Clubs" },
  { id: "46", name: "7 of Clubs" },
  { id: "47", name: "8 of Clubs" },
  { id: "48", name: "9 of Clubs" },
  { id: "49", name: "10 of Clubs" },
  { id: "50", name: "Jack of Clubs" },
  { id: "51", name: "Queen of Clubs" },
  { id: "52", name: "King of Clubs" },
];
